sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - "sbt clean test:compile"
  - "sbt coverage test"
  - "sbt coverageReport coverageAggregate"
after_success: "sbt coveralls"
